### PR TITLE
fix: Fix EOF spin loop by removing intermediate buffer in LazyConfigAcceptor

### LINKED ISSUE #85: Investigation: `LazyConfigAcceptor` potentially causes a spin loop
Hey!

Thank you for this library! We are in the process of migrating our server from rustls v0.19 to rustls v0.20 and tokio-rustls v0.23.1.

In our server, we are accepting TLS connections over `tokio::net::TcpStream`s lazy loading the certificates along the way using the `LazyConfigAcceptor`. During tests of the new version, we have seen the server go into spin loops pretty frequently (maxing out the CPU), and profiles recorded using `perf` point to the `Future` implementation of `LazyConfigAcceptor`. Precisely, to this read: https://github.com/tokio-rs/tls/blob/8519354ad6681e5ef53da7d37edde4706ccfc76f/tokio-rustls/src/lib.rs#L235

Running some quick tests, I believe the spin loop might be caused by a zero-length read from the socket, which `LazyConfigAcceptor` does not handle properly (although it should). Rustls happily accepts zero-length data, it seems:

```rust
use rustls::server::Acceptor;

fn main() {
    let mut acceptor = Acceptor::new().unwrap();

    let arr: &mut &[u8] = &mut &[][..];
    let x = acceptor.read_tls(arr).unwrap();

    assert_eq!(x, 0);
    assert!(acceptor.accept().unwrap().is_none());
}
```

... but it will also cause its `Acceptor` to return `Ok(None)` below, forcing the loop in line 258 to go round and round and round and ...

### PR DESCRIPTION
**Pull request by NeoLegends**
This PR removes the intermediate buffer (thereby also fixes #85, I believe) in `LazyConfigAcceptor`, by reusing the `AsyncRead`-`Read` bridge `Reader` struct in the common module. I believe this lets rustls read right from the `IO` passed in. 

Looking forward to your review!

### CODE REVIEW

**Comment by djc** [comment]
Thanks for your investigation and for submitting patches! I knew there might be an issue but the original reporter was never able to isolate it enough to make it easy for me to reduce, so that fell by the wayside.

Is it correct that with this PR obviates #86?

File: tokio-rustls/src/common/mod.rs [hunk 1]
```diff
@@ -343,5 +326,24 @@ where
     }
 }
 
+/// An adaptor that implements a [`Read`] interface for [`AsyncRead`] types and an
+/// associated [`Context`].
+pub struct Reader<'a, 'b, T> {
```
Comment (djc) [inline tokio-rustls/src/common/mod.rs:333]: Maybe we could give this a more descriptive name now that it's used in other places as well? Maybe something like `SyncReadAdapter`? (It appears `adapter` is a more common spelling than `adaptor`.)

**Comment by NeoLegends** [comment]
So, I was able to confirm in production that this PR seems to fix the CPU issue: 
image

This is how it looked before the fix (it immediately spiked): 
image

> Is it correct that with this PR obviates #86?

Correct.

**Review by djc — COMMENTED** [review]
This looks pretty great, gotta love changes that net remove code while fixing a bug.

Question: how hard would it be to add a test that proves that the spin loop behavior your observed can no longer happen? I think that would be a great addition.

File: tokio-rustls/src/common/mod.rs (hunk 1 above)
Comment (NeoLegends) [reply tokio-rustls/src/common/mod.rs:333]: Great idea, done :+1:

**Comment by djc** [comment]
(Out of curiosity: is netlify using rustls in production? What for?)

**Comment by NeoLegends** [comment]
Test added ✅ 

> (Out of curiosity: is netlify using rustls in production? What for?)

We're using it in the service that terminates TLS connections at the edge. I. e. all the TLS traffic we have goes through rustls actually.

**Review by quininer — APPROVED** [review]
LGTM

**Comment by djc** [comment]
@NeoLegends 0.23.2 is up on crates.io now.
